### ISSUE TITLE
Expanded MPQ causes D2R to crash upon load

### ISSUE THREAD

**Issue by ChuckHeatherly** [cyhyraethz/d2r-basic-qol#1]
I downloaded your mod on Oct 4. The basic version worked fine, but when I swapped to the extended version, D2R crashes immediately upon loading a character. I'm a software person so I'm pretty sure that I installed it right, I was previously using a different mod and it was working fine.

Oh, actually the basic version is doing one thing odd, it was saving my character files into the standard location with un-modded characters. The other mod saves character files into a subfolder called "mods/expanded", so I was expecting to find my char files in "mods/basic-qol" but that folder wasn't created.

Edit: I'm running D2R on Windows 10 64-bit Pro on an ASUS laptop.

FYI the Open an Issue here is missing the usual template I've seen on other projects that has different types of issues to create (bug report, question) and then each type has sections to guide the input like Description, Steps to Reproduce.

**Comment by cyhyraethz** [comment]
Thanks for letting me know. I received a similar report from a Reddit user a couple days ago but was unable to reproduce the problem on my machine.

I'm on vacation now and unable to do any testing as my laptop is unable to run Diablo II: Resurrected, but I'll try to look into the issue and do what I can until I get back and am able to do more testing.

Both versions should use save files from the default location since the mod is compatible with normal save files and mostly contains minor quality of life changes. 

However, if you want it to use another save file location, e.g. mods/basic-qol, that is an easy thing to change. Simply download [MPQ Editor](http://www.zezula.net/en/mpq/download.html), use it to open basic-qol.mpq, extract modinfo.json, open modinfo.json with a text editor, change "savepath" from "../" to "basic-qol", and replace the modinfo.json in basic-qol.mpq with the modified file.

Just to make sure, you installed the expanded version of basic-qol.mpq in `Diablo II Resurrected\mods\basic-qol\basic-qol.mpq, and started the game with the `-mod basic-qol` command line option, right?

I just double checked the source code and repackaged both the basic and expanded versions of basic-qol.mpq, which I have attached to this comment. If you are willing to test them for me I would appreciate it.

[basic-qol.zip](https://github.com/cyhyraethz/d2r-basic-qol/files/7291044/basic-qol.zip)
