### ISSUE TITLE
Game crash and cube disappeared from expanded stash

### ISSUE THREAD

**Issue by wzurborg** [cyhyraethz/d2r-basic-qol#3]
Not sure at all if this is related to the mod. I am running basic-qol with expanded stash. My game suddenly crashed during a LK run and after the restart my cube had disappeared from the stash. See below, is it overlapping the default stash border? Perhaps just for the records.

![grafik](https://user-images.githubusercontent.com/1320950/137635411-e7480c80-ce8c-4a84-8777-38bb590027f9.png)

**Comment by cyhyraethz** [comment]
Thank you for the report. It's always good to find out about issues like this.

I believe this may be unrelated to the mod. I heard from another modder that they received a similar bug report with their mod, and from someone else that they encountered the same issue while playing without any mods.

However, I will leave this issue open until I can find out more about this and will post another comment when I learn more.

**Comment by cyhyraethz** [comment]
I haven't learned anything else about this since my last comment. I'm going to close the issue and assume that it was a bug in the base game and not related to this mod. However, if this continues to be an issue for you and only happens when playing the mod then feel free to leave another comment and I will reopen this issue and look into it further.
