### ISSUE TITLE
Possible to merge with cbraqz simple loot filter?

### ISSUE THREAD

**Issue by abuxavier** [cyhyraethz/d2r-basic-qol#6]
I do not know nearly enough about D2 modding to understand how to do this myself, but I do know that I've thoroughly enjoyed using your basic qol mod, and I want to do Lower Kurast runs that almost require a loot filter for efficiency.  Is there an easy way to combine these?  I started down the rabbit hole of trying to figure out how to do this in cascviewer and failed miserably.

**Comment by cyhyraethz** [comment]
Sure, it's easy enough to do. I'm actually planning on releasing another version soon that won't necessarily include any changes, but will be in an easier format to combine with other mods.

Essentially it will have the game load the mod from a folder named basic-qol.mpq instead of an actual mpq file, that way if anyone wants to add another mod to it (assuming it doesn't rely on any of the same files) they can literally just put that mod's files in the basic-qol.mpq folder. The files just need to be in the proper directory structure, and the easiest way to do that would be to just copy the other mod's Data folder into the basic-qol.mpq directory and merge it with the Data folder there.

I also want to include a couple other mods' files in the download as optional addons, along with instructions on how to merge them into basic-qol (mostly just Bonesy's Expanded Storage mod and Cbraqz's D2R Simple Loot Filter).

In the meantime here's a (download link)[https://drive.google.com/drive/folders/1wMaNfAheYG8GFULtFzt1lZYw0YIIsqca?usp=sharing] for both versions of the mod (basic and expanded) with the loot filter added.

**Comment by cyhyraethz** [comment]
As for how to do it yourself, the first thing you want to do is download MPQ Editor and the Listfiles from this website:

http://www.zezula.net/en/mpq/download.html

Then you can open mpq files with MPQ Editor to extract the files from them or to add files to them. Then you could extract the Data folder from another mod, open the mod you want to add them to (e.g. basic-qol.mpq), then just drag and drop the Data folder into it. Make sure to only add the Data folder and not the modinfo.json file.

And that's it. As long as they don't both rely on modding the same game files it should work smoothly. You can check that by looking at the files in each mod using MPQ Editor before adding any files.
