### ISSUE TITLE
Stupid question: what if I accidentally run this mod with BN character?

### ISSUE THREAD

**Issue by superarts** [cyhyraethz/d2r-basic-qol#7]
Will battle.net simply reject my "play" request, or I will have the risk to get my account banned?

**Comment by cyhyraethz** [comment]
First of all, you shouldn't have to worry about that with this mod. It includes files from MilesTeg81's [Offline-Mod](https://www.nexusmods.com/diablo2resurrected/mods/28) that disable the Play and Lobby buttons in case you accidentally select the Online tab.

However, while you can't _click_ on the Play and Lobby buttons, they seem to still be selectable with a controller, so be aware of that. It looks [very different](https://staticdelivery.nexusmods.com/mods/4061/images/28/28-1633646253-2090482191.jpeg) than normal though, which should be enough to make you realize that you're playing the mod and shouldn't go online without restarting the game (Mod Info button with the name of the mod above it, Lobby button replaced with a red Disabled button, etc).

To answer your question, Battle.net still lets you go online after starting the game with a mod. I'm unsure whether or not that could result in a ban, so I highly recommend restarting the game without any mods loaded before going online.

I tried it several weeks ago to test what would happen, and while mods obvious don't work online, there were some noticeable side effects. For example, while I couldn't teleport in town, the teleport icon was white instead of grey (indicating it was castable), and when I tried to use it the casting animation would trigger but nothing else would happen.

**Comment by superarts** [comment]
Thank you! Very detailed explanation!
