### ISSUE TITLE
add cow portal recipe

### ISSUE THREAD

**Issue by LV99VIVI** [cyhyraethz/d2r-basic-qol#8]
add a new cow recipe so we dont have to find wirts leg everytime. make it like 1 tome and 1 scroll of town portal.

keep old recipe for people that dont want to cheat it. im going to make my own in the meantime.

**Comment by cyhyraethz** [comment]
Good idea. I'll add that when I have time.

**Comment by LV99VIVI** [comment]
found it out i made it like this

Tome of Town Portal -> Portal to The Secret Cow Level	1			0	28				1	tbk							Cow Portal																																																																																							0

**Comment by LV99VIVI** [comment]
[line to add to make cow level with only tome of tp.txt](https://github.com/cyhyraethz/d2r-basic-qol/files/7909303/line.to.add.to.make.cow.level.with.only.tome.of.tp.txt)

**Comment by cyhyraethz** [comment]
I used to do something similar to that by removing the merc mod files from the expanded storage mod. The problem is needing to do that every time the expanded storage mod is updated. It also contains large files and packaging multiple versions of the mod is not an ideal solution.

I could add instructions on which files to delete from the expanded storage mod to remove certain features (merc mod, expanded inventory, etc). That might be easier to maintain as more updates to the expanded storage mod are released.

**Comment by cyhyraethz** [comment]
Added the new cube recipe for cow portal in 26256c36f527079bdc77e7f6c7f7a49c2fb96298
